# Generated by Django 5.2.7 on 2025-10-04 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewCotegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotegory_name', models.CharField(max_length=64)),
                ('cotegory_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_name', models.CharField(max_length=256)),
                ('new_description', models.TextField()),
                ('news_date', models.DateTimeField(auto_now_add=True)),
                ('new_cotegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proapp.newcotegory')),
            ],
        ),
    ]
